config/routes.rb
Rails.application.routes.draw do
  
  # メインページへのルート
  root              'spendings#index'
  resources :spendings, only: [:index, :new, :create, :destroy]
  
end

app/models/spending.rb
class Spending < ActiveRecord::Base
  
  # 「カテゴリ」のバリデーション
  validates :category,  presence: true
  
  # 「金額」のバリデーション
  VALID_AMOUNT_REGEX = /\A[1-9]+[0-9]*\z/
  validates :amount,    presence: true, length: { maximum: 6 },
                        format: { with: VALID_AMOUNT_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/spendings_controller.rb
class SpendingsController < ApplicationController
  before_action :detect_devise_variant
  
  # 支出記録を表示
  def index
    if (params[:switch].to_i == 0) 
      @day = Time.now.month      # 最初に表示する月を、ウィンドウから取得
    else
      @day = params[:switch].to_i   # 次に表示する月を、パラメータから取得
    end
    @spendings = Spending.where(month: @day).order('day DESC')    # 次に表示する月のレコードを降順で取得
    
    @spending = Spending.new
  end
  
  # 支出記録を保存
  def create
    @spending = Spending.new(spending_params)
    if @spending.save
      redirect_to :back
    else
      redirect_to :back, :alert => '"金額"が無効な値です'
    end
  end
  
  # 支出記録を削除
  def destroy
    Spending.find(params[:id]).destroy
    redirect_to :back
  end
  
  private
    
    # StrongParameter
    def spending_params
      params.require(:spending).permit(:month, :day, :category, :amount)
    end
    
    # ビューのモバイル対応
    def detect_devise_variant
      case request.user_agent
      when /iPhone/
        request.variant = :iphone
      when /Android/
        request.variant = :android
      end
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/spendings_helper.rb
module SpendingsHelper

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BudgetBook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, install-scale=1">
</head>
<body>
  
  <!-- エラーメッセージのパーシャル -->
  <%= render 'spendings/error_messages' %>
  
  <%= yield %>

</body>
</html>

app/views/spendings/_error_messages.html.erb
<div class="container">
  <% flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: "#{message_type} #{message_type}-danger") %>
  <% end %>
</div>

app/views/spendings/_form.html.erb
<div class="form-horizontal" form="role">
<%= form_for(@spending) do |f| %>

  <!--月選択フォーム-->
  <div class="form-group">
    <%= f.label :月, class: "col-sm-2 col-xs-2" %>
    <div class="col-sm-2 col-xs-2">
      <%= f.select :month, (1..12).map { |p| [p] }, :selected => Time.now.month, class: "form-control col-sm-6" %>
    </div>
  </div>

  <!-- 日選択フォーム -->
  <div class="form-group">
    <%= f.label :日, class: "col-sm-2 col-xs-2" %>
    <div class="col-sm-2 col-xs-2">
      <%= f.select :day, (1..31).map { |p| [p] }, :selected => Time.now.day, class: "form-control col-sm-6" %>
    </div>
  </div>

  <!-- カテゴリ選択フォーム -->
  <div class="form-group">
    <%= f.label :カテゴリ, class: "col-sm-2 col-xs-2" %>
    <div class="col-sm-3 col-xs-2">
    <%= f.select :category, ['朝食', '昼食', '夕食',
                             '趣味', '旅行', '交際',
                             '食材', '家賃', 'その他'], class: "form-control" %>
    </div>
  </div>
  
  <!-- 金額入力フォーム  -->
  <div class="form-group">
    <%= f.label :金額, class: "col-sm-2 col-xs-2" %>
    <div class="col-sm-3 col-xs-3">
      <%= f.text_field :amount, class: "form-control input-sm" %>
    </div>
  </div>

  <!-- 記録ボタン -->
  <%= f.submit "記録", class: "btn btn-primary mrg" %>
<% end %>
</div>

app/views/spendings/_mobile_form.html.erb
<div class="form-horizontal" form="role">
<%= form_for(@spending) do |f| %>

  <!--月選択フォーム-->
  <div class="form-group">
    <%= f.label :月, class: "formSize" %>
    <div class="formSize">
      <%= f.select :month, (1..12).map { |p| [p] }, :selected => Time.now.month, class: "form-control" %>
    </div>
  </div>

  <!-- 日選択フォーム -->
  <div class="form-group">
    <%= f.label :日, class: "formSize" %>
    <div class="formSize">
      <%= f.select :day, (1..31).map { |p| [p] }, :selected => Time.now.day, class: "form-control" %>
    </div>
  </div>

  <!-- カテゴリ選択フォーム -->
  <div class="form-group">
    <%= f.label :カテゴリ, class: "formSize" %>
    <div class="formSize">
    <%= f.select :category, ['朝食', '昼食', '夕食',
                             '趣味', '旅行', '交際',
                             '食材', '家賃', 'その他'], class: "form-control" %>
    </div>
  </div>
  
  <!-- 金額入力フォーム  -->
  <div class="form-group">
    <%= f.label :金額, class: "formSize" %>
    <div class="formSize">
      <%= f.text_field :amount, class: "form-control input-sm" %>
    </div>
  </div>

  <!-- 記録ボタン -->
  <%= f.submit "記録", class: "btn btn-primary mrg" %>
<% end %>
</div>

app/views/spendings/_spending_list.html.erb
<% @spendings.each do |spending| %>
  <tr>
    <td><%= spending.month %></td>
    <td><%= spending.day %></td>
    <td><%= spending.category %></td>
    <td><%= number_to_currency(spending.amount, :unit => '￥' ) %></td>
    <td><%= link_to '削除', spending, method: :delete, class: "btn btn-danger btn-sm" %></td>
  </tr>
<% end %>

app/views/spendings/_sum_amount.html.erb
<!-- 合計支出額 -->
<div class="panel panel-default">
  <div class="panel-heading">
    合計支出額
  </div>
  <div class="panel-body">
    <%= number_to_currency(Spending.where(month: @day).sum(:amount), :unit => '￥') %>   <!-- 月毎の合計を表示 -->
  </div>
</div>

app/views/spendings/index.html+android.erb
<div class="container">
  <!-- 合計支出額 -->
  <div>
    <div style="margin-top:20px;">
      <%= render 'spendings/sum_amount' %>
    </div>
  </div>
  
  <!-- メインカラム -->
  <!-- 支出した月の表示 -->
  <div class="month">
    <div class="before">
      <% if @day != 1 %>
        <%= link_to "#{@day-1}月", spendings_path(:switch => @day - 1), class: "btn btn-info"%>
      <% end %>
    </div>
    
    <h1 class="head"><%= @day %>月</h1>
    
    <div class="after">
      <% if @day != 12 %>
        <%= link_to "#{@day+1}月", spendings_path(:switch => @day + 1), class: "btn btn-info"%>
      <% end %>
    </div>
  </div>
      
  <!-- 支出リスト 見出し -->
  <table class="table">
    <thead>
      <tr>
        <th>月</th>
        <th>日</th>
        <th>カテゴリ</th>
        <th>金額</th>
        <th></th>
      </tr>
    </thead>
    
    <!-- 支出リスト 内容 -->
    <tbody>
      <!-- 支出リストを作成する処理 -->
      <%= render 'spendings/spending_list' %>
    </tbody>
  </table>
  
  <!-- 記録するボタン -->
  <div class="record" style="margin-bottom:30px;">
    <a data-toggle="modal" href="#myModal" class="btn btn-primary">記録する</a>
  </div>

<!--入力フォームのポップアップ -->
<div class="modal fade" id="myModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">支出記録</h4>
      </div>
      <div class="modal-body" style="height:244px;">
        <%= render 'spendings/mobile_form' %>
      </div>
    </div>
  </div>
</div>

app/views/spendings/index.html+iphone.erb
<div class="container">
  <!-- 合計支出額 -->
  <div>
    <div style="margin-top:20px;">
      <%= render 'spendings/sum_amount' %>
    </div>
  </div>
  
  
  <!-- メインカラム -->
  <!-- 支出した月の表示 -->
  <div class="month">
    <div class="before">
      <% if @day != 1 %>
        <%= link_to "#{@day-1}月", spendings_path(:switch => @day - 1), class: "btn btn-info"%>
      <% end %>
    </div>
    
    <h1 class="head"><%= @day %>月</h1>
    
    <div class="after">
      <% if @day != 12 %>
        <%= link_to "#{@day+1}月", spendings_path(:switch => @day + 1), class: "btn btn-info"%>
      <% end %>
    </div>
  </div>
  
  <!-- 支出リスト 見出し -->
  <table class="table">
    <thead>
      <tr>
        <th>月</th>
        <th>日</th>
        <th>カテゴリ</th>
        <th>金額</th>
        <th></th>
      </tr>
    </thead>
    
    <!-- 支出リスト 内容 -->
    <tbody>
      <!-- 支出リストを作成する処理 -->
      <%= render 'spendings/spending_list' %>
    </tbody>
  </table>
    
  <!-- 記録するボタン -->
  <div class="record" style="margin-bottom:30px;">
    <a data-toggle="modal" href="#myModal" class="btn btn-primary">記録する</a>
  </div>
  

<!--入力フォームのポップアップ -->
<div class="modal fade" id="myModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">支出記録</h4>
      </div>
      <div class="modal-body" style="height:244px;">
        <%= render 'spendings/mobile_form' %>
      </div>
    </div>
  </div>
</div>

app/views/spendings/index.html.erb
<div class="container">
  <div class="row" style="margin-top:20px;">
    <!-- サイドバー -->
    <div class="col-sm-2 col-sm-offset-1 sideHead">
      <%= render 'spendings/sum_amount' %>
      
      <!-- 記録するボタン -->
      <div class="record" style="margin-bottom:30px;">
        <a data-toggle="modal" href="#myModal" class="btn btn-primary">記録する</a>
      </div>
    </div>
    
    
    <!-- メインカラム -->
    <div class="col-sm-8">
     
      <!-- 支出した月の表示 -->
      <div class="row"  style="margin-bottom:10px;" >
        <div class="col-xs-1 col-xs-offset-1">
          <% if @day != 1 %>
            <%= link_to "#{@day-1}月", spendings_path(:switch => @day - 1), class: "btn btn-info top"%>
          <% end %>
        </div>
        <div class="col-xs-6 col-xs-offset-1">
          
        <h1><%= @day %>月</h1>
        
        </div>
        <div class="col-xs-offset-1 col-xs-1" sytle="margin-top:20px;">
          <% if @day != 12 %>
            <%= link_to "#{@day+1}月", spendings_path(:switch => @day + 1), class: "btn btn-info top"%>
          <% end %>
        </div>
      </div>
      
      <!-- 支出リスト 見出し -->
      <table class="table">
        <thead>
          <tr>
            <th>月</th>
            <th>日</th>
            <th>カテゴリ</th>
            <th>金額</th>
            <th></th>
          </tr>
        </thead>
        
        <!-- 支出リスト 内容 -->
        <tbody>
          <!-- 支出リストを作成する処理 -->
          <%= render 'spendings/spending_list' %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<!--入力フォームのポップアップ -->
<div class="modal fade" id="myModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">支出記録</h4>
      </div>
      <div class="modal-body" style="height:244px;">
        <%= render 'spendings/form' %>
      </div>
    </div>
  </div>
</div>